# Generated by Django 4.1 on 2022-08-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(default='Web Design', max_length=50)),
                ('url', models.URLField()),
                ('desc', models.TextField(null=True)),
                ('desc2', models.TextField(null=True)),
                ('logo', models.ImageField(upload_to='logo')),
                ('photo1', models.ImageField(upload_to='portfolio')),
                ('photo2', models.ImageField(upload_to='portfolio')),
                ('photo3', models.ImageField(blank=True, upload_to='portfolio')),
            ],
        ),
    ]
