# Generated by Django 4.1 on 2022-09-06 07:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='con',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
    ]
