# Generated by Django 4.1 on 2022-09-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_portfolio_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='content',
        ),
    ]
